### PR TITLE
Monitor for unobserved errors

### LINKED ISSUE #48: Add "unobserved" exception handling
> An “unobserved” exception is one that’s stored into the task but then never looked at in any way by the consuming code.  There are many ways of observing the exception, including Wait()’ing on the Task, accessing a Task<TResult>’s Result, looking at the Task’s Exception property, and so on.  If code never observes a Task’s exception, then when the Task goes away, the TaskScheduler.UnobservedTaskException gets raised, giving the application one more opportunity to “observe” the exception.  And if the exception still remains unobserved, the exception escalation policy is then enabled by the exception going unhandled on the finalizer thread.

> ...exceptions indicate something has gone wrong, and crashing helps developers to immediately identify that the application has entered an unreliable state.

(Source: http://blogs.msdn.com/b/pfxteam/archive/2011/09/28/task-exception-handling-in-net-4-5.aspx)

In .NET, "unobserved" exceptions will bubble up and intentionally crash the application. This would be a useful feature to allow developers to be notified (via a crash) of an "unobserved" exception since it means their application has entered an unreliable state.

Since this would be a breaking change, it might be worthwhile to disable this feature by default and require it to be explicitly turned on by developers.

### PR DESCRIPTION
**Pull request by stefanrusek**
This defers the actual finalization handling to a secondary class.
Additionally if any of the continuations immediately observe the error,
then no additional finalization logic is performed.

Fixes #48

### CODE REVIEW

**Comment by richardjrossiii** [comment]
I like the concept, and it seems like a fairly portable API to have everywhere. My one concern, however, is that `finalize()` is not guaranteed to be called on a user-controlled thread (in fact, on the desktop JVM, all finalizers are run on a dedicated thread), which makes the uncaught exception handler bit somewhat useless.

**Comment by stefanrusek** [comment]
@richardjrossiii The fact that it runs on a GC thread doesn't make it useless. It might prevent that handler from directly calling UI methods, but it could still log the error someplace useful. Also the default handler could fire off a new Task to deal with the error like so:

    final Executor myUIExecutor = ...;
    Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
        public void uncaughtException(Thread t, Throwable e) {
            Task.Call(new Callable<Void>() {
                // anything you want to do..
            }, myUIExecutor);
        }
    });

**Comment by grantland** [comment]
This looks interesting! I want to play around with this to see how this plays out in different environments. 

If it works well, we'd also want this configurable and off by default to not be a breaking change and so developers can turn it off in production environments.

**Comment by stefanrusek** [comment]
To turn it off by default, we could just add a static field and getUnobservedExceptionHandler() and setUnobservedExceptionHandler() methods. the default would just eat the exception. Then use that instead of Thread.getDefaultUncaughExceptionHandler().

**Comment by stefanrusek** [comment]
@grantland I made it configurable and added a test.

**Comment by grantland** [comment]
FYI, I'll be without a computer until December and won't be able to take a look at this until then. Hope that's ok and sorry!

**Comment by stefanrusek** [comment]
@grantland Had a chance to look at this?

**Comment by stefanrusek** [comment]
@grantland ping

**Comment by grantland** [comment]
Finally got around to playing around with it and it's awesome! Thanks for updating it so that it doesn't throw on the uncaught exception handler by default.

@hallucinogen mind taking a look at the API and giving a second opinion?

File: bolts-tasks/src/main/java/bolts/UnobservedErrorNotifier.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+  @Override
+  protected void finalize() throws Throwable {
+    Task faultedTask = this.task;
+    if (faultedTask != null) {
+      Task.UnobservedExceptionHandler ueh = Task.getUnobservedExceptionHandler();
+      if (ueh != null) {
+        ueh.unobservedException(faultedTask, new UnobservedTaskException(faultedTask.getError()));
+      }
+    }
+  }
```
Comment (grantland) [inline bolts-tasks/src/main/java/bolts/UnobservedErrorNotifier.java]: one small edit: we should be using `try { ... } finally { super.finalize() }` here

File: bolts-tasks/src/main/java/bolts/UnobservedErrorNotifier.java [hunk 2]
```diff
@@ -0,0 +1,33 @@
+package bolts;
+
+/**
+ * This class is used to retain a faulted task until either its error is observed or it is
+ * finalized. If it is finalized with a task, then the uncaught exception handler is exected
+ * with an UnobservedTaskException.
+ */
+public class UnobservedErrorNotifier {
```
Comment (grantland) [inline bolts-tasks/src/main/java/bolts/UnobservedErrorNotifier.java]: we probably want to make this package private

File: bolts-tasks/src/main/java/bolts/Task.java [hunk 3]
```diff
@@ -47,11 +47,54 @@
...
+    return unobservedExceptionHandler;
+  }
+
+  /**
+   * Set the handler invoked when a task has an unobserved exception.
+   * @param eh the object to use as an unobserved exception handler. If
+   *           <tt>null</tt> then unobserved exceptions will be ignored.
+   */
+  public static void setUnobservedExceptionHandler(UnobservedExceptionHandler eh) {
+    unobservedExceptionHandler = eh;
```
Comment (hallucinogen) [inline bolts-tasks/src/main/java/bolts/Task.java]: will we need some kind of lock here? I can see possible race condition

File: bolts-tasks/src/main/java/bolts/UnobservedErrorNotifier.java (hunk 2 above)
Comment (hallucinogen) [inline bolts-tasks/src/main/java/bolts/UnobservedErrorNotifier.java]: +1

File: bolts-tasks/src/main/java/bolts/Task.java [hunk 4]
```diff
@@ -47,11 +47,54 @@
...
+   * @see #setUnobservedExceptionHandler
+   */
+  public interface UnobservedExceptionHandler {
+    /**
+     * Method invoked when the given task has an unobserved exception.
+     * <p>Any exception thrown by this method will be ignored.
+     * @param t the task
+     * @param e the exception
+     */
+    void unobservedException(Task<?> t, UnobservedTaskException e);
```
Comment (hallucinogen) [inline bolts-tasks/src/main/java/bolts/Task.java]: oh right. In Java isn't this usually in some form of `onUnobservedException`

Comment (grantland) [inline bolts-tasks/src/main/java/bolts/Task.java]: This currently matches `Thread.UncaughtExceptionHandler`'s pattern: https://developer.android.com/reference/java/lang/Thread.UncaughtExceptionHandler.html

File: bolts-tasks/src/main/java/bolts/Task.java (hunk 3 above)
Comment (grantland) [inline bolts-tasks/src/main/java/bolts/Task.java]: `volatile` should protect us here, no?

Comment (hallucinogen) [inline bolts-tasks/src/main/java/bolts/Task.java]: oh right I didn't see that.

File: bolts-tasks/src/main/java/bolts/Task.java (hunk 4 above)
Comment (hallucinogen) [inline bolts-tasks/src/main/java/bolts/Task.java]: lgtm then

**Comment by grantland** [comment]
Last nit is to hide `UnobservedErrorNotifier`

**Comment by stefanrusek** [comment]
@grantland updated visibility

**Comment by grantland** [comment]
Thanks for you're awesome contribution! As a thank you, wed like to send you some Parse swag. If you're interested, send me your mailing address and t-shirt size to my email address on my profile page.
